//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Invoice_Medicine = new HashSet<Invoice_Medicine>();
            this.Invoice_Service = new HashSet<Invoice_Service>();
        }
    
        public int id { get; set; }
        public Nullable<int> appointment_id { get; set; }
        public Nullable<int> prescription_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public int nurse_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Nurse Nurse { get; set; }
        public virtual Prescription Prescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Medicine> Invoice_Medicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Service> Invoice_Service { get; set; }
    }
}
